### ISSUE TITLE
你这个 编译upnp正常不？

### ISSUE THREAD

**Issue by lalasou** [chika0801/ImmortalWrt-RedmiAX6000#1]
我编译很多次不正常（比特彗星检测失败），
替换了openwrt 18.06里面老版本upnp才正常

但是  x-wrt 也是新版本 他那个就正常😅

**Comment by chika0801** [comment]
upnp 我加过，试过一次，是编译成功的，我平时不用UPNP，就取消这个了。

**Comment by chika0801** [comment]
> 我编译很多次不正常（比特彗星检测失败）， 替换了openwrt 18.06里面老版本upnp才正常
> 
> 但是 x-wrt 也是新版本 他那个就正常😅

今天看到这个ISS，我想起之前有人问我，回来想@你有解决方法了。没想到就是大佬你自己解决的666

**Comment by chika0801** [comment]
你如果遇到编译xray go 版本出错 参考 https://github.com/chika0801/ImmortalWrt-RedmiAX6000/blob/54907cad2130cb34a69e1c48de4f5c22222ffc3e/.github/workflows/build-openwrt.yml#L76

我今天就是研究这问题去了

**Comment by lalasou** [comment]
> 你如果遇到编译xray go 版本出错 参考 https://github.com/chika0801/ImmortalWrt-RedmiAX6000/blob/54907cad2130cb34a69e1c48de4f5c22222ffc3e/.github/workflows/build-openwrt.yml#L76
> 
> 
> 
> 我今天就是研究这问题去了

好的   多谢🤩
